### ISSUE TITLE
Redux Version?

### ISSUE THREAD

**Issue by brianblakely** [ZethRyder/Disk-Expansion#1]
It would be great to use the d-pad for ocarina and boots. I personally had no luck creating a hybrid patch. Thank you for this mod!

The "Redux" in question, if not clear: https://www.romhacking.net/hacks/5138/

**Comment by ZethRyder** [comment]
While I understand enhancements like that would help with certain aspects of the game such as the water temple.  However it would require a lot more work having to disassemble someone else's work to figure out what they even did and weeks more of testing to make sure there is no bug/crashes on emulators and hardware.  It's just not worth it.
